import { Platform, StyleSheet } from 'react-native';

import { COLORS, SCREEN_H } from './constants';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLORS.skyTop,
    overflow: 'hidden',
  },
  sky: {
    ...StyleSheet.absoluteFillObject,
  },
  skyGrad1: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: SCREEN_H * 0.5,
    backgroundColor: COLORS.skyTop,
  },
  skyGrad2: {
    position: 'absolute',
    top: SCREEN_H * 0.2,
    left: 0,
    right: 0,
    height: SCREEN_H * 0.35,
    backgroundColor: COLORS.skyMid,
    opacity: 0.7,
  },
  skyGrad3: {
    position: 'absolute',
    top: SCREEN_H * 0.4,
    left: 0,
    right: 0,
    height: SCREEN_H * 0.25,
    backgroundColor: COLORS.skyBottom,
    opacity: 0.6,
  },
  star: {
    position: 'absolute',
    backgroundColor: COLORS.starColor,
  },
  moon: {
    position: 'absolute',
    top: 50,
    right: 40,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#fffbe0',
    shadowColor: '#fffbe0',
    shadowOpacity: 0.9,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  moonInner: {
    width: '100%',
    height: '100%',
    borderRadius: 26,
    backgroundColor: '#fffbe0',
    overflow: 'hidden',
  },
  crater: {
    position: 'absolute',
    backgroundColor: 'rgba(200,190,150,0.4)',
    borderRadius: 50,
  },
  moonGlow: {
    position: 'absolute',
    top: -20,
    left: -20,
    right: -20,
    bottom: -20,
    borderRadius: 50,
    backgroundColor: 'rgba(255,251,224,0.15)',
  },
  ground: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 55,
    backgroundColor: COLORS.ground,
  },
  groundTop: {
    height: 8,
    backgroundColor: COLORS.groundTop,
  },
  groundMid: {
    height: 4,
    backgroundColor: COLORS.soilDark,
    opacity: 0.6,
  },
  soilLines: {
    paddingTop: 6,
    paddingHorizontal: 8,
    gap: 4,
  },
  soilLine: {
    height: 2,
    backgroundColor: COLORS.soilDark,
    borderRadius: 1,
    marginBottom: 4,
  },
  fog: {
    position: 'absolute',
    bottom: 50,
    left: 0,
    right: 0,
    height: 40,
    backgroundColor: 'rgba(60,160,70,0.08)',
  },
  fogLight: {
    position: 'absolute',
    bottom: 55,
    left: 0,
    right: 0,
    height: 25,
    backgroundColor: 'rgba(100,200,100,0.04)',
  },
  cornField: {
    position: 'absolute',
    bottom: 50,
    left: 0,
    right: 0,
    height: 220,
  },
  cornContainer: {
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
  },
  kvWrapper: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 24,
  },
  contentStack: {
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
  },
  logoArea: {
    alignItems: 'center',
    marginBottom: 28,
  },
  logoIcon: {
    width: 76,
    height: 76,
    borderRadius: 24,
    backgroundColor: COLORS.stemGreen,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: COLORS.leafLight,
    shadowOpacity: 0.5,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 4 },
    elevation: 12,
    borderWidth: 2,
    borderColor: 'rgba(77,200,90,0.4)',
  },
  appName: {
    fontSize: 34,
    fontWeight: '700',
    color: COLORS.white,
    letterSpacing: -0.5,
    marginBottom: 4,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  appTagline: {
    fontSize: 13,
    color: COLORS.link,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    opacity: 0.9,
    textAlign: 'center',
  },
  card: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 28,
    padding: 26,
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.2)',
    shadowColor: '#000',
    shadowOpacity: 0.6,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 10 },
    elevation: 15,
    marginBottom: 18,
  },
  cardHeader: {
    marginBottom: 18,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.white,
    marginBottom: 6,
    letterSpacing: -0.4,
  },
  cardDescription: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.textGray,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.link,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
    opacity: 0.9,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.inputBg,
    borderWidth: 1.5,
    borderColor: COLORS.inputBorder,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'ios' ? 15 : 11,
    gap: 12,
  },
  inputWrapperFocused: {
    borderColor: COLORS.inputFocus,
    backgroundColor: 'rgba(77,200,90,0.08)',
  },
  inputIcon: {
    opacity: 0.9,
  },
  input: {
    flex: 1,
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '400',
    padding: 0,
    margin: 0,
  },
  eyeIcon: {
    opacity: 0.75,
  },
  errorBox: {
    backgroundColor: 'rgba(192,57,43,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(192,57,43,0.3)',
    borderRadius: 12,
    padding: 12,
  },
  errorSlot: {
    minHeight: 16,
    justifyContent: 'flex-start',
    marginBottom: 8,
  },
  errorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  errorText: {
    color: '#ff8a80',
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
  },
  btnLogin: {
    backgroundColor: COLORS.btnGreen,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    shadowColor: COLORS.btnLight,
    shadowOpacity: 0.4,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.35)',
  },
  btnDisabled: {
    opacity: 0.7,
  },
  btnText: {
    color: COLORS.white,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  btnLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  forgotBtn: {
    alignItems: 'center',
    marginTop: 18,
  },
  forgotText: {
    color: COLORS.textGray,
    fontSize: 13,
  },
  forgotLink: {
    color: COLORS.link,
    fontWeight: '600',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 22,
    gap: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  dividerText: {
    color: COLORS.textGray,
    fontSize: 11,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  profileBadge: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 14,
  },
  avatarBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(77,200,90,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeCopy: {
    flex: 1,
  },
  badgeName: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
  },
  badgeRole: {
    color: COLORS.offWhite,
    fontSize: 11,
    opacity: 0.8,
    letterSpacing: 0.3,
    marginTop: 3,
    lineHeight: 15,
  },
});
