import { StyleSheet } from 'react-native';

import { THEME } from './constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: THEME.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: 'rgba(10,31,13,0.95)',
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  addButton: {
    backgroundColor: THEME.green,
  },
  title: { color: THEME.white, fontSize: 24, fontWeight: '800' },
  subtitle: { color: THEME.muted, fontSize: 12, marginTop: 2 },
  content: { padding: 16, gap: 16 },
  heroCard: {
    backgroundColor: THEME.card,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: THEME.border,
    padding: 14,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 12,
  },
  searchInput: { flex: 1, color: THEME.white, fontSize: 14, padding: 0 },
  filterRow: { gap: 8, paddingBottom: 12 },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  filterChipText: { color: THEME.muted, fontSize: 12, fontWeight: '700' },
  filterChipTextActive: { color: THEME.white },
  mapFrame: {
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: THEME.border,
    position: 'relative',
  },
  map: { width: '100%', height: 280 },
  centerButton: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(10,31,13,0.92)',
    borderWidth: 1,
    borderColor: THEME.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapFallback: {
    minHeight: 220,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: THEME.border,
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 20,
  },
  mapFallbackTitle: { color: THEME.white, fontSize: 15, fontWeight: '700' },
  mapFallbackText: { color: THEME.muted, fontSize: 13, lineHeight: 18, textAlign: 'center' },
  detailsCard: {
    backgroundColor: THEME.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: THEME.border,
    padding: 16,
  },
  detailsHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 10 },
  detailsHeaderActions: { alignItems: 'flex-end', gap: 8 },
  detailsTitle: { color: THEME.white, fontSize: 20, fontWeight: '800', marginBottom: 4 },
  detailsSubtitle: { color: THEME.muted, fontSize: 13 },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: THEME.gold,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  editButtonText: {
    color: THEME.bg,
    fontSize: 11,
    fontWeight: '800',
  },
  statusBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  statusText: { fontSize: 11, fontWeight: '800' },
  infoRow: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  infoIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  infoLabel: {
    color: THEME.muted,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  infoValue: { color: THEME.offWhite, fontSize: 13, lineHeight: 18 },
  listSection: { gap: 12 },
  listTitle: { color: THEME.white, fontSize: 18, fontWeight: '700' },
  paginationToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 6,
  },
  paginationMainInfo: {
    flex: 1,
    gap: 6,
  },
  paginationModeControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  modeButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  modeButtonActive: {
    backgroundColor: 'rgba(77,200,90,0.18)',
    borderColor: THEME.green,
  },
  modeButtonText: {
    color: THEME.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  modeButtonTextActive: {
    color: THEME.white,
  },
  paginationText: { color: THEME.muted, fontSize: 12 },
  pageSizeControls: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pageSizeButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  pageSizeButtonActive: { backgroundColor: 'rgba(77,200,90,0.18)', borderColor: THEME.green },
  pageSizeText: { color: THEME.muted, fontSize: 11, fontWeight: '800' },
  pageSizeTextActive: { color: THEME.white },
  pageNumberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  pageNavButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  pageNavButtonDisabled: { opacity: 0.4 },
  pageNavText: { color: THEME.white, fontSize: 11, fontWeight: '700' },
  pageNavTextDisabled: { color: 'rgba(255,255,255,0.5)' },
  pageNumberButton: {
    paddingVertical: 6,
    paddingHorizontal: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  pageNumberButtonActive: { backgroundColor: THEME.green, borderColor: THEME.green },
  pageNumberText: { color: THEME.white, fontSize: 11, fontWeight: '700' },
  pageNumberTextActive: { color: THEME.bg },
  pageDots: { color: THEME.muted, fontSize: 11, paddingVertical: 6, paddingHorizontal: 8 },
  centerBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 28, gap: 10 },
  centerText: { color: THEME.muted, fontSize: 13 },
  emptyState: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    backgroundColor: 'rgba(245,200,66,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245,200,66,0.24)',
    borderRadius: 16,
    padding: 14,
  },
  emptyText: { color: THEME.offWhite, fontSize: 13, flex: 1 },
  propertyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: THEME.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: THEME.border,
    padding: 14,
  },
  propertyCardActive: {
    borderColor: THEME.borderStrong,
    backgroundColor: 'rgba(10,36,15,0.98)',
  },
  propertyIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyName: { color: THEME.white, fontSize: 14, fontWeight: '700', marginBottom: 3 },
  propertyMeta: { color: THEME.muted, fontSize: 12, lineHeight: 17 },
  ownerCtaCard: {
    marginTop: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(245,200,66,0.24)',
    backgroundColor: 'rgba(245,200,66,0.08)',
    padding: 14,
    gap: 14,
  },
  ownerCtaHeader: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  ownerCtaIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245,200,66,0.12)',
  },
  ownerCtaTitle: {
    color: THEME.white,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 4,
  },
  ownerCtaText: {
    color: THEME.offWhite,
    fontSize: 12,
    lineHeight: 18,
  },
  ownerForm: {
    gap: 12,
  },
  inlineField: {
    gap: 6,
  },
  inlineLabel: {
    color: THEME.white,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  inlineInputBox: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  inlineInput: {
    color: THEME.white,
    fontSize: 14,
    padding: 0,
  },
  inlineInputError: {
    borderColor: THEME.red,
  },
  inlineErrorText: {
    color: THEME.red,
    fontSize: 11,
  },
  ownerSearchText: {
    color: THEME.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  ownerOptionsCard: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: THEME.border,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  ownerOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  ownerOptionIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(77,200,90,0.12)',
  },
  ownerOptionName: {
    color: THEME.white,
    fontSize: 13,
    fontWeight: '700',
  },
  ownerOptionMeta: {
    color: THEME.muted,
    fontSize: 12,
    marginTop: 2,
  },
  ownerEmailStatus: {
    fontSize: 12,
    fontWeight: '700',
  },
  ownerFeedback: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  ownerFeedbackOk: {
    backgroundColor: 'rgba(77,200,90,0.12)',
    borderColor: 'rgba(77,200,90,0.28)',
  },
  ownerFeedbackErr: {
    backgroundColor: 'rgba(255,107,107,0.12)',
    borderColor: 'rgba(255,107,107,0.28)',
  },
  ownerFeedbackText: {
    color: THEME.offWhite,
    fontSize: 12,
    lineHeight: 18,
  },
  ownerActions: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  ownerPrimaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: THEME.gold,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 44,
    flex: 1,
  },
  ownerPrimaryButtonText: {
    color: THEME.bg,
    fontSize: 13,
    fontWeight: '800',
  },
  ownerGhostButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ownerGhostButtonText: {
    color: THEME.white,
    fontSize: 13,
    fontWeight: '700',
  },
});
