import { StyleSheet } from 'react-native';

import { INSTRUTORES_THEME as THEME } from './constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: THEME.skyTop },
  content: { padding: 20, paddingTop: 56, paddingBottom: 120 },
  title: { fontSize: 28, fontWeight: '800', color: THEME.white, marginBottom: 6 },
  subtitle: { fontSize: 14, color: THEME.textMuted, marginBottom: 18, lineHeight: 20 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: THEME.cardBg,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.14)',
    marginBottom: 18,
  },
  searchInput: { flex: 1, color: THEME.white, fontSize: 15 },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: THEME.leafLight,
    borderRadius: 14,
    paddingVertical: 14,
    marginBottom: 18,
  },
  addButtonText: { color: THEME.white, fontSize: 14, fontWeight: '800' },
  loadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 18,
  },
  loadingText: { color: THEME.textMuted, fontSize: 13 },
  emptyState: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(245,200,66,0.14)',
    borderColor: 'rgba(245,200,66,0.24)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    marginBottom: 18,
  },
  emptyText: { color: THEME.offWhite, fontSize: 13, flex: 1 },
  card: {
    backgroundColor: THEME.cardBg,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.12)',
    marginBottom: 12,
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(77,200,90,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  avatarText: { color: THEME.leafLight, fontWeight: '800' },
  cardCopy: { flex: 1 },
  cardTitle: { color: THEME.white, fontSize: 15, fontWeight: '700', marginBottom: 2 },
  cardMeta: { color: THEME.textMuted, fontSize: 12, marginBottom: 8 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  roleBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(91,156,255,0.16)',
  },
  roleBadgeText: { color: THEME.blue, fontSize: 11, fontWeight: '700' },
  regionalBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(245,200,66,0.14)',
  },
  regionalBadgeText: {
    color: THEME.offWhite,
    fontSize: 11,
    fontWeight: '700',
  },
  statusBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  statusActive: { backgroundColor: 'rgba(77,200,90,0.18)' },
  statusInactive: { backgroundColor: 'rgba(255,107,107,0.18)' },
  statusText: { color: THEME.white, fontSize: 11, fontWeight: '700' },
  detailBox: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
    padding: 14,
    gap: 10,
  },
  detailBoxWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
  sectionTitle: { color: THEME.white, fontSize: 16, fontWeight: '700', marginBottom: 2, width: '100%' },
  sectionTitleWide: { marginBottom: 4 },
  editSectionCard: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  editSectionCardWide: {
    width: '48.5%',
  },
  editSectionCardSpanFull: {
    width: '100%',
  },
  editSectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 2,
  },
  editSectionIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editSectionTitle: {
    color: THEME.white,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  editSectionSubtitle: {
    color: THEME.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  label: { color: THEME.offWhite, fontSize: 13, fontWeight: '700', marginTop: 4 },
  helperText: { color: THEME.textMuted, fontSize: 12, marginTop: 6, marginBottom: 8 },
  input: {
    backgroundColor: THEME.inputBg,
    borderWidth: 1,
    borderColor: THEME.inputBorder,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: THEME.white,
    fontSize: 14,
  },
  permissionGrid: {
    gap: 10,
  },
  permissionCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 5,
  },
  permissionCardActive: {
    backgroundColor: 'rgba(91,156,255,0.14)',
    borderColor: 'rgba(91,156,255,0.32)',
  },
  permissionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  permissionCardTitle: {
    color: THEME.white,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
  },
  permissionCardTitleActive: {
    color: THEME.white,
  },
  permissionCardMeta: {
    color: THEME.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  permissionCardMetaActive: {
    color: THEME.offWhite,
  },
  regionalGrid: {
    gap: 10,
  },
  regionalCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  regionalCardActive: {
    backgroundColor: 'rgba(77,200,90,0.14)',
    borderColor: 'rgba(77,200,90,0.3)',
  },
  regionalCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  regionalCardTitle: {
    color: THEME.white,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
  },
  regionalCardTitleActive: {
    color: THEME.white,
  },
  regionalCardMeta: {
    color: THEME.textMuted,
    fontSize: 12,
  },
  regionalCardMetaActive: {
    color: THEME.offWhite,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    padding: 14,
    marginTop: 4,
  },
  switchCopy: { flex: 1 },
  switchTitle: { color: THEME.white, fontSize: 14, fontWeight: '700', marginBottom: 4 },
  switchDescription: { color: THEME.textMuted, fontSize: 12, lineHeight: 18 },
  switchStatus: { marginTop: 8, fontSize: 12, fontWeight: '700' },
  switchStatusActive: { color: THEME.leafLight },
  switchStatusInactive: { color: THEME.error },
  inactiveWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: 'rgba(245,200,66,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245,200,66,0.24)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inactiveWarningText: {
    color: THEME.offWhite,
    fontSize: 12,
    lineHeight: 18,
    flex: 1,
  },
  feedbackBox: { borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, borderWidth: 1 },
  feedbackSuccess: { backgroundColor: 'rgba(77,200,90,0.15)', borderColor: 'rgba(77,200,90,0.35)' },
  feedbackError: { backgroundColor: 'rgba(255,107,107,0.15)', borderColor: 'rgba(255,107,107,0.35)' },
  feedbackText: { color: THEME.white, fontSize: 13, fontWeight: '600', lineHeight: 18 },
  saveButton: {
    marginTop: 4,
    backgroundColor: THEME.blue,
    borderRadius: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  saveButtonText: { color: THEME.white, fontSize: 14, fontWeight: '800' },
  secondaryButton: {
    backgroundColor: 'rgba(245,200,66,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(245,200,66,0.28)',
    borderRadius: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  secondaryButtonText: { color: THEME.white, fontSize: 14, fontWeight: '700' },
  propertiesSection: {
    marginTop: 6,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  propertiesHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  manageAssignmentsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(91,156,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(91,156,255,0.28)',
  },
  manageAssignmentsButtonText: {
    color: THEME.white,
    fontSize: 12,
    fontWeight: '700',
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    paddingHorizontal: 6,
    gap: 8,
  },
  paginationMainInfo: {
    flex: 1,
    gap: 6,
  },
  paginationModeControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  modeButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  modeButtonActive: {
    backgroundColor: 'rgba(77,200,90,0.18)',
    borderColor: THEME.leafLight,
  },
  modeButtonText: {
    color: THEME.offWhite,
    fontSize: 12,
    fontWeight: '700',
  },
  modeButtonTextActive: {
    color: '#fff',
  },
  paginationText: {
    color: THEME.offWhite,
    fontSize: 12,
    opacity: 0.9,
  },
  paginationButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pageButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  pageButtonDisabled: {
    opacity: 0.4,
  },
  pageButtonText: {
    color: THEME.white,
    fontSize: 12,
    fontWeight: '700',
  },
  pageButtonTextDisabled: {
    color: 'rgba(255,255,255,0.55)',
  },
  pageSizeControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pageSizeButton: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  pageSizeButtonActive: {
    backgroundColor: 'rgba(77,200,90,0.18)',
    borderColor: THEME.leafLight,
  },
  pageSizeText: {
    color: THEME.white,
    fontSize: 12,
    fontWeight: '700',
  },
  pageSizeTextActive: {
    color: THEME.white,
  },
  pageNumberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 10,
    marginBottom: 10,
    flexWrap: 'wrap',
  },
  pageNavButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  pageNavButtonDisabled: {
    opacity: 0.4,
  },
  pageNavText: {
    color: THEME.white,
    fontSize: 12,
    fontWeight: '700',
  },
  pageNavTextDisabled: {
    color: 'rgba(255,255,255,0.55)',
  },
  pageNumberButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  pageNumberButtonActive: {
    backgroundColor: 'rgba(77,200,90,0.18)',
    borderColor: THEME.leafLight,
  },
  pageNumberText: {
    color: THEME.white,
    fontSize: 12,
    fontWeight: '700',
  },
  pageNumberTextActive: {
    color: THEME.white,
  },
  pageDots: {
    color: THEME.offWhite,
    fontSize: 14,
    paddingHorizontal: 6,
  },
  propertiesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  emptyProperties: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    padding: 14,
  },
  emptyPropertiesText: { color: THEME.textMuted, fontSize: 13, lineHeight: 18 },
  propertyCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  propertyIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245,200,66,0.16)',
  },
  propertyCopy: { flex: 1 },
  propertyName: { color: THEME.white, fontSize: 14, fontWeight: '700', marginBottom: 2 },
  propertyMeta: { color: THEME.offWhite, fontSize: 12, marginBottom: 4 },
  propertyProject: { color: THEME.textMuted, fontSize: 12 },
});
