import { StyleSheet } from 'react-native';

import { THEME } from './constants';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  root: { flex: 1, backgroundColor: THEME.skyTop },
  pickupWrapper: {
    position: 'absolute',
    top: 0,
    left: 16,
    right: 16,
    zIndex: 20,
  },
  pickupCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 8,
  },
  pickupSuccess: {
    backgroundColor: 'rgba(46,175,109,0.96)',
    borderColor: 'rgba(255,255,255,0.14)',
  },
  pickupError: {
    backgroundColor: 'rgba(198,64,64,0.96)',
    borderColor: 'rgba(255,255,255,0.14)',
  },
  pickupIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickupIconSuccess: {
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  pickupIconError: {
    backgroundColor: 'rgba(0,0,0,0.16)',
  },
  pickupText: {
    flex: 1,
    color: THEME.white,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  content: { padding: 20, paddingTop: 56, paddingBottom: 80 },
  headerRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 20 },
  backButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.08)', alignItems: 'center', justifyContent: 'center' },
  headerCopy: { flex: 1 },
  title: { color: THEME.white, fontSize: 28, fontWeight: '800', marginBottom: 6 },
  subtitle: { color: THEME.textMuted, fontSize: 14, lineHeight: 20 },
  card: { backgroundColor: THEME.cardBg, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: 'rgba(77,200,90,0.15)' },
  noticeBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: 'rgba(245,200,66,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245,200,66,0.28)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 6,
  },
  noticeText: {
    flex: 1,
    color: THEME.offWhite,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  label: { color: THEME.offWhite, fontSize: 13, fontWeight: '700', marginBottom: 8, marginTop: 10 },
  input: { backgroundColor: THEME.inputBg, borderWidth: 1, borderColor: THEME.inputBorder, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, color: THEME.white, fontSize: 14 },
  selectorSection: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    padding: 12,
    gap: 10,
  },
  selectorHint: {
    color: THEME.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  selectorGrid: {
    gap: 10,
  },
  loadingRegionais: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6, paddingVertical: 8 },
  loadingRegionaisText: { color: THEME.textMuted, fontSize: 12, fontWeight: '600' },
  selectorCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  selectorCardActive: {
    backgroundColor: 'rgba(77,200,90,0.12)',
    borderColor: 'rgba(77,200,90,0.35)',
  },
  selectorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  selectorTitle: {
    color: THEME.white,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
  },
  selectorTitleActive: {
    color: THEME.white,
  },
  selectorDescription: {
    color: THEME.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  selectorDescriptionActive: {
    color: THEME.offWhite,
  },
  submitButton: { marginTop: 18, backgroundColor: THEME.blue, borderRadius: 14, paddingVertical: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
  submitText: { color: THEME.white, fontSize: 15, fontWeight: '800' },
});
