import { StyleSheet } from 'react-native';

import { THEME } from './constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: THEME.skyTop },
  skyBg: { position: 'absolute', top: 0, left: 0, right: 0, backgroundColor: THEME.skyTop },
  moon: { position: 'absolute', top: 45, right: 30, width: 42, height: 42, borderRadius: 21, backgroundColor: '#fffbe0', shadowColor: '#fffbe0', shadowOpacity: 0.8, shadowRadius: 20, elevation: 8 },
  moonInner: { width: '100%', height: '100%', borderRadius: 21, overflow: 'hidden' },
  crater: { position: 'absolute', backgroundColor: 'rgba(200,190,150,0.4)', borderRadius: 50 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 60 },
  header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 24 },
  welcomeBox: { flex: 1, paddingRight: 14 },
  welcomeText: { fontSize: 14, color: THEME.textMuted, marginBottom: 4 },
  userName: { fontSize: 26, fontWeight: '700', color: THEME.white, marginBottom: 8 },
  roleBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(91,156,255,0.15)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, gap: 6 },
  roleText: { fontSize: 11, color: THEME.blue, fontWeight: '600' },
  metaRow: { flexDirection: 'row', flexWrap: 'nowrap', alignItems: 'center', gap: 10, marginTop: 12, marginBottom: 12 },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  metaPillText: {
    fontSize: 12,
    color: THEME.offWhite,
    fontWeight: '600',
  },
  headerSummary: {
    fontSize: 13,
    color: THEME.offWhite,
    lineHeight: 19,
    maxWidth: 440,
  },
  notifBtn: { width: 44, height: 44, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.08)', alignItems: 'center', justifyContent: 'center' },
  notifDot: { position: 'absolute', top: 10, right: 10, width: 8, height: 8, borderRadius: 4, backgroundColor: THEME.error },
  statsGrid: { gap: 12, marginBottom: 28 },
  statCard: {
    minHeight: 150,
    backgroundColor: THEME.cardBg,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.12)',
    justifyContent: 'space-between',
  },
  statCardLarge: {
    width: '100%',
    minHeight: 172,
    paddingVertical: 20,
  },
  statCardMain: {
    width: '100%',
  },
  statSummaryCard: {
    width: '100%',
    minHeight: 0,
    paddingTop: 16,
    paddingBottom: 16,
  },
  statSummaryCardWide: {
    paddingHorizontal: 20,
  },
  statCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  statIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  statValue: { fontSize: 32, fontWeight: '700', color: THEME.white, marginBottom: 8, lineHeight: 36 },
  statLabel: {
    fontSize: 13,
    color: THEME.offWhite,
    lineHeight: 18,
    fontWeight: '600',
    maxWidth: '90%',
  },
  statTrend: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(77,200,90,0.12)',
  },
  trendText: { fontSize: 12, color: THEME.leafLight, fontWeight: '600' },
  statSummaryHeader: {
    marginBottom: 14,
  },
  statSummaryTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: THEME.white,
    marginBottom: 4,
  },
  statSummarySubtitle: {
    fontSize: 12,
    color: THEME.textMuted,
  },
  statSummaryList: {
    gap: 10,
  },
  statSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minHeight: 44,
  },
  statSummaryLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  statSummaryIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statSummaryLabel: {
    fontSize: 13,
    color: THEME.offWhite,
    fontWeight: '600',
  },
  statSummaryValue: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '700',
    color: THEME.white,
  },
  statSummaryDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  section: { marginBottom: 24 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: THEME.white },
  seeAll: { fontSize: 13, color: THEME.link, fontWeight: '600' },
  alertsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  alertCard: {
    backgroundColor: THEME.cardBg,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.1)',
    minHeight: 118,
    justifyContent: 'space-between',
  },
  alertCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  alertTopLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  alertIconBox: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  alertHeadlineBox: { flex: 1, minWidth: 0 },
  alertLabel: { fontSize: 13, fontWeight: '700', color: THEME.white, marginBottom: 4 },
  alertMessage: { fontSize: 13, fontWeight: '500', color: THEME.offWhite, lineHeight: 19 },
  alertTime: { fontSize: 11, color: THEME.textMuted },
  emptyState: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: 'rgba(77,200,90,0.12)', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: 'rgba(77,200,90,0.18)' },
  emptyText: { color: THEME.offWhite, fontSize: 13, flex: 1 },
  quickActions: { marginBottom: 20 },
  actionsRow: { flexDirection: 'row', gap: 12, marginTop: 14 },
  actionCard: { flex: 1, backgroundColor: THEME.cardBg, borderRadius: 16, padding: 16, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(77,200,90,0.12)' },
  actionCardGhost: { flex: 1, opacity: 0 },
  actionIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  actionText: { fontSize: 11, fontWeight: '600', color: THEME.offWhite, textAlign: 'center' },
});
