import { StyleSheet } from 'react-native';

import { AUDITORIA_THEME as THEME } from './constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: THEME.skyTop },
  skyGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: THEME.skyMid,
    opacity: 0.9,
  },
  content: { paddingHorizontal: 20 },
  header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16, marginBottom: 22 },
  headerCopy: { flex: 1, minWidth: 0 },
  eyebrow: { color: THEME.leafLight, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', marginBottom: 8 },
  title: { fontSize: 28, lineHeight: 34, fontWeight: '800', color: THEME.white, marginBottom: 8 },
  subtitle: { fontSize: 14, lineHeight: 21, color: THEME.offWhite, maxWidth: 620 },
  headerIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: 'rgba(77,200,90,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 26 },
  summaryGridWide: { flexWrap: 'nowrap' },
  summaryCard: {
    width: '48%',
    minHeight: 132,
    backgroundColor: THEME.cardBg,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.cardBorder,
    justifyContent: 'space-between',
  },
  summaryCardWide: { flex: 1, width: undefined },
  summaryIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  summaryValue: { color: THEME.white, fontSize: 27, lineHeight: 32, fontWeight: '800' },
  summaryLabel: { color: THEME.textMuted, fontSize: 12, fontWeight: '700' },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  sectionTitle: { color: THEME.white, fontSize: 18, fontWeight: '800' },
  sectionMeta: { color: THEME.textMuted, fontSize: 12, fontWeight: '700' },
  instructorList: { gap: 12, marginBottom: 26 },
  instructorSkeleton: {
    backgroundColor: THEME.cardBg,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.cardBorder,
    alignItems: 'center',
    gap: 8,
  },
  instructorCard: {
    backgroundColor: THEME.cardBg,
    borderRadius: 18,
    padding: 15,
    borderWidth: 1,
    borderColor: THEME.cardBorder,
  },
  instructorTop: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14 },
  instructorRank: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  instructorRankText: { fontSize: 15, fontWeight: '900' },
  instructorCopy: { flex: 1, minWidth: 0 },
  instructorName: { color: THEME.white, fontSize: 15, fontWeight: '800', marginBottom: 3 },
  instructorMeta: { color: THEME.textMuted, fontSize: 12 },
  instructorScoreBox: { alignItems: 'flex-end', minWidth: 74 },
  instructorScore: { fontSize: 24, lineHeight: 28, fontWeight: '900' },
  instructorScoreLabel: { color: THEME.textMuted, fontSize: 10, fontWeight: '700' },
  instructorStats: { flexDirection: 'row', gap: 8 },
  instructorStat: {
    flex: 1,
    minWidth: 0,
    backgroundColor: 'rgba(255,255,255,0.055)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  instructorStatValue: { color: THEME.white, fontSize: 17, fontWeight: '900', marginBottom: 3 },
  instructorStatLabel: { color: THEME.textMuted, fontSize: 10, fontWeight: '700', textAlign: 'center' },
  drilldownCard: {
    backgroundColor: 'rgba(10,31,13,0.94)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(245,200,66,0.2)',
    marginBottom: 18,
  },
  detailCard: {
    backgroundColor: 'rgba(10,31,13,0.96)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(91,156,255,0.2)',
    marginBottom: 18,
  },
  drilldownHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 14 },
  drilldownTitleBox: { flex: 1, minWidth: 0 },
  drilldownEyebrow: { color: THEME.gold, fontSize: 11, fontWeight: '900', textTransform: 'uppercase', marginBottom: 5 },
  drilldownTitle: { color: THEME.white, fontSize: 18, lineHeight: 23, fontWeight: '900', marginBottom: 3 },
  drilldownSubtitle: { color: THEME.textMuted, fontSize: 12, lineHeight: 17 },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlineState: {
    minHeight: 70,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
  },
  visitList: { gap: 10 },
  visitListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.055)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    padding: 12,
  },
  visitIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  visitCopy: { flex: 1, minWidth: 0 },
  visitProperty: { color: THEME.white, fontSize: 13, fontWeight: '800', marginBottom: 3 },
  visitMeta: { color: THEME.textMuted, fontSize: 11, lineHeight: 16 },
  visitScoreBadge: {
    minWidth: 48,
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 7,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  visitScoreText: { fontSize: 15, fontWeight: '900' },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 10 },
  detailItem: {
    width: '48%',
    minWidth: 0,
    backgroundColor: 'rgba(255,255,255,0.055)',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  pythonAuditBlock: {
    backgroundColor: 'rgba(77,200,90,0.075)',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(77,200,90,0.15)',
    marginBottom: 10,
  },
  pythonAuditHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  pythonAuditTitle: { color: THEME.white, fontSize: 13, fontWeight: '900' },
  photosBlock: {
    backgroundColor: 'rgba(91,156,255,0.075)',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(91,156,255,0.16)',
    marginBottom: 12,
  },
  photoList: { gap: 12, paddingRight: 4 },
  photoCard: {
    width: 180,
    backgroundColor: 'rgba(255,255,255,0.055)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
    paddingBottom: 10,
  },
  visitPhoto: { width: '100%', height: 126, backgroundColor: 'rgba(255,255,255,0.05)' },
  photoMissing: {
    width: '100%',
    height: 126,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  photoName: { color: THEME.white, fontSize: 12, fontWeight: '800', marginTop: 9, marginHorizontal: 10 },
  photoMeta: { color: THEME.textMuted, fontSize: 10, lineHeight: 15, marginHorizontal: 10, marginTop: 3 },
  auditCard: {
    backgroundColor: THEME.cardBg,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.cardBorder,
    marginBottom: 14,
  },
  auditHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 14 },
  auditTitleBox: { flex: 1, minWidth: 0 },
  propertyName: { color: THEME.white, fontSize: 16, fontWeight: '800', marginBottom: 4 },
  auditMeta: { color: THEME.textMuted, fontSize: 12, lineHeight: 17 },
  trackingCode: { color: THEME.leafLight, fontSize: 11, fontWeight: '800', marginTop: 6 },
  riskBadge: { minWidth: 88, borderRadius: 16, paddingVertical: 8, paddingHorizontal: 10, borderWidth: 1, alignItems: 'center' },
  riskScore: { fontSize: 23, lineHeight: 27, fontWeight: '900' },
  riskLabel: { fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  evidenceRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  evidenceItem: {
    flex: 1,
    minWidth: 0,
    backgroundColor: 'rgba(255,255,255,0.055)',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  evidenceLabel: { color: THEME.textMuted, fontSize: 11, fontWeight: '700', marginBottom: 5 },
  evidenceValue: { color: THEME.offWhite, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  indicatorGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 4 },
  indicatorCard: {
    width: '48%',
    minHeight: 136,
    backgroundColor: 'rgba(255,255,255,0.045)',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  indicatorTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 9 },
  indicatorIcon: { width: 30, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  indicatorValue: { flex: 1, minWidth: 0, textAlign: 'right', fontSize: 11, fontWeight: '800' },
  indicatorLabel: { color: THEME.white, fontSize: 12, fontWeight: '800', marginBottom: 5 },
  indicatorDetail: { color: THEME.textMuted, fontSize: 11, lineHeight: 16 },
  rulesCard: {
    backgroundColor: THEME.cardBg,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(91,156,255,0.18)',
    marginTop: 4,
  },
  rulesHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 14 },
  rulesCopy: { flex: 1, minWidth: 0 },
  rulesIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(91,156,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rulesTitle: { color: THEME.white, fontSize: 15, fontWeight: '800', marginBottom: 3 },
  rulesSubtitle: { color: THEME.textMuted, fontSize: 12 },
  ruleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginTop: 10 },
  ruleText: { flex: 1, color: THEME.offWhite, fontSize: 12, lineHeight: 18 },
  stateCard: {
    backgroundColor: THEME.cardBg,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: THEME.cardBorder,
    alignItems: 'center',
    marginBottom: 14,
    gap: 8,
  },
  stateIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  stateTitle: { color: THEME.white, fontSize: 15, fontWeight: '800', textAlign: 'center' },
  stateText: { color: THEME.textMuted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
});
