import { StyleSheet } from 'react-native';

import { ATRIBUICOES_TECNICO_THEME as THEME } from './constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: THEME.bg },
  content: { padding: 20, paddingTop: 56, paddingBottom: 110, gap: 16 },
  header: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  title: { color: THEME.white, fontSize: 28, fontWeight: '800', marginBottom: 4 },
  subtitle: { color: THEME.muted, fontSize: 14, lineHeight: 20 },
  loadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
  },
  loadingText: { color: THEME.muted, fontSize: 13 },
  sectionCard: {
    backgroundColor: THEME.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: THEME.border,
    padding: 16,
    gap: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  currentLinksCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 14,
    gap: 10,
  },
  currentLinksHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  currentLinksTitle: {
    color: THEME.white,
    fontSize: 14,
    fontWeight: '800',
  },
  currentLinksMeta: {
    color: THEME.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  currentLinksEmpty: {
    color: THEME.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  linkedPropertyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    padding: 12,
  },
  linkedPropertyCopy: {
    flex: 1,
  },
  linkedPropertyTitle: {
    color: THEME.white,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 2,
  },
  linkedPropertyMeta: {
    color: THEME.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  unlinkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,107,107,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,107,107,0.28)',
  },
  unlinkButtonText: {
    color: THEME.white,
    fontSize: 12,
    fontWeight: '700',
  },
  sectionTitle: { color: THEME.white, fontSize: 17, fontWeight: '800' },
  sectionSubtitle: { color: THEME.muted, fontSize: 13, lineHeight: 18 },
  summaryPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(77,200,90,0.14)',
  },
  summaryPillText: { color: THEME.offWhite, fontSize: 12, fontWeight: '700' },
  paginationToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  paginationText: { color: THEME.offWhite, fontSize: 12, opacity: 0.9, flex: 1 },
  pageSizeControls: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pageSizeButton: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  pageSizeButtonActive: {
    backgroundColor: 'rgba(77,200,90,0.18)',
    borderColor: THEME.green,
  },
  pageSizeText: { color: THEME.white, fontSize: 12, fontWeight: '700' },
  pageSizeTextActive: { color: THEME.white },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: THEME.inputBg,
    borderWidth: 1,
    borderColor: THEME.inputBorder,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  searchInput: { flex: 1, color: THEME.white, fontSize: 14, padding: 0 },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 12,
  },
  optionCardActive: {
    backgroundColor: 'rgba(91,156,255,0.14)',
    borderColor: 'rgba(91,156,255,0.28)',
  },
  optionCopy: { flex: 1 },
  optionTitle: { color: THEME.white, fontSize: 14, fontWeight: '700', marginBottom: 2 },
  optionMeta: { color: THEME.muted, fontSize: 12, lineHeight: 17 },
  propertyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 12,
  },
  propertyCardActive: {
    backgroundColor: 'rgba(77,200,90,0.12)',
    borderColor: 'rgba(77,200,90,0.28)',
  },
  checkBox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxActive: {
    backgroundColor: THEME.green,
    borderColor: THEME.green,
  },
  pageNumberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 6,
    flexWrap: 'wrap',
  },
  pageNavButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  pageNavButtonDisabled: { opacity: 0.4 },
  pageNavText: { color: THEME.white, fontSize: 12, fontWeight: '700' },
  pageNavTextDisabled: { color: 'rgba(255,255,255,0.55)' },
  pageNumberButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  pageNumberButtonActive: {
    backgroundColor: 'rgba(77,200,90,0.18)',
    borderColor: THEME.green,
  },
  pageNumberText: { color: THEME.white, fontSize: 12, fontWeight: '700' },
  pageNumberTextActive: { color: THEME.white },
  pageDots: { color: THEME.offWhite, fontSize: 14, paddingHorizontal: 6 },
  statusBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  statusActive: { backgroundColor: 'rgba(77,200,90,0.18)' },
  statusInactive: { backgroundColor: 'rgba(255,107,107,0.18)' },
  statusText: { color: THEME.white, fontSize: 11, fontWeight: '700' },
  feedbackBox: { borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, borderWidth: 1 },
  feedbackSuccess: { backgroundColor: 'rgba(77,200,90,0.15)', borderColor: 'rgba(77,200,90,0.35)' },
  feedbackError: { backgroundColor: 'rgba(255,107,107,0.15)', borderColor: 'rgba(255,107,107,0.35)' },
  feedbackText: { color: THEME.white, fontSize: 13, fontWeight: '600', lineHeight: 18 },
  saveButton: {
    marginTop: 4,
    backgroundColor: THEME.blue,
    borderRadius: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  saveButtonText: { color: THEME.white, fontSize: 14, fontWeight: '800' },
});
